server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-d705tg8gjchc73d17e80-a.ohio-postgres.render.com/usuarios_db_cgk8
spring.datasource.username=ian
spring.datasource.password=HwRcjfkJucnbPqCvqcaNZW9ANYgmmj6B
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/swagger-ui.html